name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: descargar repostorio
        uses: actions/checkout@v3
      - name: instalar aplicaci√≥n en Tomcat
        run: |
          mvn package -DskipTests=true
          cp -r target/Baloncesto /usr/local/tomcat/webapps
          - name: preparar base de datos de prueba
          run: |
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_PASS="clave"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
      - name: realizar pruebas funcionales
        run: |
        mvn failsafe:integration-test failsafe:verify




  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pruebas-funcionales
        run: echo "pruebas-funcionales"

  qa:
    needs: test
    runs-on: self-hosted
    steps:
      - name: calidad-codigo
        run: echo "calidad-codigo"

  deploy:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: despliegue
        run: echo "despliegue"